//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.03 at 01:51:46 PM PYST 
//


package py.com.edge.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the py.com.edge.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: py.com.edge.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaveNewSkillRequest }
     * 
     */
    public SaveNewSkillRequest createSaveNewSkillRequest() {
        return new SaveNewSkillRequest();
    }

    /**
     * Create an instance of {@link ResponseUserSkill }
     * 
     */
    public ResponseUserSkill createResponseUserSkill() {
        return new ResponseUserSkill();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link SaveNewSkillResponse }
     * 
     */
    public SaveNewSkillResponse createSaveNewSkillResponse() {
        return new SaveNewSkillResponse();
    }

    /**
     * Create an instance of {@link SaveNewUserRequest }
     * 
     */
    public SaveNewUserRequest createSaveNewUserRequest() {
        return new SaveNewUserRequest();
    }

    /**
     * Create an instance of {@link SkillObject }
     * 
     */
    public SkillObject createSkillObject() {
        return new SkillObject();
    }

    /**
     * Create an instance of {@link GetAllUserRequest }
     * 
     */
    public GetAllUserRequest createGetAllUserRequest() {
        return new GetAllUserRequest();
    }

    /**
     * Create an instance of {@link GetUserAndSkillResponse }
     * 
     */
    public GetUserAndSkillResponse createGetUserAndSkillResponse() {
        return new GetUserAndSkillResponse();
    }

    /**
     * Create an instance of {@link SkillsUser }
     * 
     */
    public SkillsUser createSkillsUser() {
        return new SkillsUser();
    }

    /**
     * Create an instance of {@link SaveNewSkillRequest.Skill }
     * 
     */
    public SaveNewSkillRequest.Skill createSaveNewSkillRequestSkill() {
        return new SaveNewSkillRequest.Skill();
    }

    /**
     * Create an instance of {@link GetUserAndSkillRequest }
     * 
     */
    public GetUserAndSkillRequest createGetUserAndSkillRequest() {
        return new GetUserAndSkillRequest();
    }

    /**
     * Create an instance of {@link SaveNewUserResponse }
     * 
     */
    public SaveNewUserResponse createSaveNewUserResponse() {
        return new SaveNewUserResponse();
    }

    /**
     * Create an instance of {@link NewUserResponse }
     * 
     */
    public NewUserResponse createNewUserResponse() {
        return new NewUserResponse();
    }

    /**
     * Create an instance of {@link GetAllUserResponse }
     * 
     */
    public GetAllUserResponse createGetAllUserResponse() {
        return new GetAllUserResponse();
    }

    /**
     * Create an instance of {@link UsersArray }
     * 
     */
    public UsersArray createUsersArray() {
        return new UsersArray();
    }

    /**
     * Create an instance of {@link ResponseUserSkill.Response }
     * 
     */
    public ResponseUserSkill.Response createResponseUserSkillResponse() {
        return new ResponseUserSkill.Response();
    }

}
