//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.02 at 02:33:18 AM PYST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://edge.com.py/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package py.com.edge.soap;
