//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.03 at 01:51:46 PM PYST 
//


package py.com.edge.soap.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for skillItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="skillItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idSkill" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="skillName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "skillItem", propOrder = {
    "idSkill",
    "skillName"
})
public class SkillItem {

    protected int idSkill;
    @XmlElement(required = true)
    protected String skillName;

    /**
     * Gets the value of the idSkill property.
     * 
     */
    public int getIdSkill() {
        return idSkill;
    }

    /**
     * Sets the value of the idSkill property.
     * 
     */
    public void setIdSkill(int value) {
        this.idSkill = value;
    }

    /**
     * Gets the value of the skillName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkillName() {
        return skillName;
    }

    /**
     * Sets the value of the skillName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkillName(String value) {
        this.skillName = value;
    }

}
